### PR TITLE
fix(agent): add removeDuplicatedLineSuffix postprocess filter

### PR DESCRIPTION
**Pull request by erfanium**
here is my attempt to fix `clients/tabby-agent/src/postprocess/golden/remove_duplication/duplicated_line_suffix.toml` test.
I also tested this on a daily usage. the fix just works fine.

but currently not all the tests are passing, because of a logical interference in `removeDuplicatedLineSuffix` and `calculateReplaceRange` filters. `removeDuplicatedLineSuffix` approach is to trim the input. but `calculateReplaceRange` approach is to keep the current input and modify the replaceRange.

should i refactor this filter and move it under replaceRange filter categories?

### CODE REVIEW

**Comment by icycodes** [comment]
Hi, @erfanium!

Thank you for your PR!

I noticed that the filter `removeDuplicatedLineSuffix` seems to handle many cases that the `calculateReplaceRange` or `trimMultiLineInSingleLineMode` should handle.

Let me explain the current filters:

The `calculateReplaceRange`: 
If the current line suffix characters are all auto-closing characters like `)` and `]`, which should be deleted when applying the suggestion, I think they should be included in the replace range.

The `trimMultiLineInSingleLineMode`: 
If the current line suffix characters contain non-auto-closing characters, it means that the user is filling in a line. Therefore, the completion is expected to be a single line. 
In this case, if the server-generated completion is multi-line, I only keep the first line and remove the duplicated suffix. If the server-generated completion is just one line, it mostly appears to be a good FIM case, so I keep it as is.

I remember that you mentioned in the Slack channel that you forked the tabby server source and added checking for multi-line or single-line generation, with `\n` as a stop character for the single-line case. I think this is the only case that `removeDuplicatedLineSuffix` can handle but `trimMultiLineInSingleLineMode` can not.

I'm not entirely sure about this, so please correct me if I'm misunderstanding.

**Comment by wsxiaoys** [comment]
Closing as this is stale

**Comment by erfanium** [comment]
@icycodes I'm so sorry. I had totally forgotten this PR.

>  I think this is the only case that removeDuplicatedLineSuffix can handle but trimMultiLineInSingleLineMode can not.

do you think tabby-agent should handle this scenario (server returning only the first line)? If yes, I can fix this PR based on your suggestions

**Comment by icycodes** [comment]
> @icycodes I'm so sorry. I had totally forgotten about this PR.
> 
> > I think this is the only case that removeDuplicatedLineSuffix can handle but trimMultiLineInSingleLineMode can not.
> 
> do you think tabby-agent should handle this scenario (server returning only the first line)? If yes, I can fix this PR based on your suggestions

I think it should be handled. 
When the server returned only one line, I assumed it was a good FIM result and skipped the post-processing. However, it seems that this assume is not correct. 

It's not recommended to add a new filter because `trimMultiLineInSingleLineMode` has already processing for `mode == "fill-in-line" && inputLines.length > 1`. I think that adding some code here for `inputLines.length == 1` would be a simpler approach. We could rename this filter to something like `trimSuffixInSingleLineMode`.

**Comment by erfanium** [comment]
going to reopen a new pr for this

**Pull request closed without merging**
