### PR TITLE
fix(docs): correct typos

### PR DESCRIPTION
**Pull request by HKABIG**
Fixed some Typos

### CODE REVIEW

**Comment by HKABIG** [comment]
@wsxiaoys please review this changes

**Comment by wsxiaoys** [comment]
Thank you for the pull request. It's greatly appreciated.

The only comment I have is that I would prefer to continue using 'favorite' and 'behavior' as they are more commonly used in the US. Could you update the PR?

**Comment by HKABIG** [comment]
Yes I will update the PR

**Comment by HKABIG** [comment]
@wsxiaoys I committed the requested changes please review

**Comment by wsxiaoys** [comment]
Thank you!

**Pull request merged**
