### PR TITLE
M1 Mac support

### PR DESCRIPTION
**Pull request by glennfu**
I have this project now working on my M1 Mac well enough that I can visit `http://127.0.0.1:8081/#/default/completions_v1_completions_post` and do a successful test post of the binarysearch completions example. Skimming the logs, the only clear error remaining is this:
```
2023-04-11 12:12:00,170 DEBG 'dagu_scheduler' stdout output:
2023/04/11 12:12:00 Failed to start DAG: fork/exec ./tabby/tools/analytic/main.sh: no such file or directory
```

Some notes:
* My strategy was to avoid Docker since the benefit of Metal would be lost unless I ran this natively
* I added a few instruction changes to the README.md that I used to get things set up on my local machine
* I had to replace the absolutely path of `/data` with the relative path of `data` in many instances. I don't know how to write that in a backward compatible way.
* I added `torchvision` and `supervisor` to `pyproject.toml`. I experimented with some ways to make it ONLY install on the Mac to not affect the original Dockerfile behavior but couldn't get it to work. I'm a Python novice and today is the first time I even heard of `poetry` so it's probably entirely possible for someone else to fix.

I hope this helps you speed this project along! Like I said, I'm a Python novice, but I'm very interested in this project and eager to assist. Let me know what else I can do to help.

### CODE REVIEW

**Comment by glennfu** [comment]
Oh I forgot one more thing: I changed to port 5001 because there's a core macos process that runs on 5000 and conflicts with this.

**Comment by wsxiaoys** [comment]
Thank you for submitting the PR. It provides a great reference point for the mps device support. However, we won't be able to merge it.

To achieve complete support, adding an arm docker image would be better, and we should remove all the fine-tuning stuff as it's unlikely that we'll fine-tune on a Mac client.

Nevertheless, we appreciate your contribution and will mark this PR as draft for referencing purposes.

**Comment by glennfu** [comment]
If the goal is to have performant M1 Mac support, and not just slow emulation, I don't believe it will be possible to achieve that using Docker.

**Comment by wsxiaoys** [comment]
implemented in #66

**Pull request closed without merging**
