### PR TITLE
feat(eclipse): Add client plugin for Eclipse IDE

### PR DESCRIPTION
**Pull request by selamanse**
This PR adds a client project for an eclipse ide plugin developed with the eclipse ide package for eclipse committers (https://www.eclipse.org/downloads/packages/release/2023-09/r/eclipse-ide-eclipse-committers)

It acts as an proposal compute engine that also completes the code based on tabby completion responses.

In its current state it only has a setting page in eclipse and uses the IJavaCompletionProposalComputer Interface to generate proposals. After plugin activation the Proposals will be in the default proposal list after successful retrieval.

Tested with Tabby 0.3.1 and model StarCoder-1B on M1 Metal

Addresses #356

### CODE REVIEW

**Comment by selamanse** [comment]
@wsxiaoys 
My outstanding todos:
- I will add a github actions workflow for testing according to the other client plugins
- and also artifact release step within that workflow if thats ok since I do not have an eclipse marketplace account. 

Can you please:
- guide me what further needs to be implemented in this "initial" plugin implementation?
- add the `hacktoberfest-accepted` label to this PR ? It would be awesome. thx

**Comment by icycodes** [comment]
Hi, @selamanse 

Thank you for your contributions! We greatly appreciate your efforts to help improve Tabby.

However, I have some concerns that I would like to explain.

One of the main reasons is that I found that this plugin directly sends requests to the Tabby server, which may not be the optimal approach. We have designed a common client agent that serves as an intermediary between the IDE and the Tabby server. This agent provides several useful functions such as request debouncing, caching, completion post-processing, and more. By utilizing the agent, we can avoid duplicating these functionalities in every IDE plugin.  
The agent interface is not yet stable enough to be published as a standard protocol, we are actively working on it. If you would like more details, you can refer to the IntelliJ plugin we have implemented, which starts a child process running the agent and communicates with it via stdio. This plugin is implemented in Kotlin, which should be similar to Java.

On another note, we aim to achieve a consistent user experience by displaying inline completion as ghost text. I am not familiar with the Eclipse plugin, so I'm unsure if it is possible to achieve this behavior in Eclipse.

We will keep this PR open and release the Tabby agent protocol in the near future. We will also provide a detailed document to assist the community in implementing IDE plugins.

Once again, we sincerely appreciate your contribution, and thank you for your patience as we work on finalizing the agent protocol.

**Comment by selamanse** [comment]
@icycodes thank you for the explanation and your thoughts this helps a lot to get things in context. I'm happy to be able to contribute as this project is fun and useful at the same time.

as for the agent integration - I realized the other two plugin projects integrated tabby-agent but did not fully understand why. It kind of makes sense when you explain it. I can change my proposal to integrate the tabby-agent in the same way the others do it is not a problem.
Since I am new to eclipse plugin development I wanted to keep things within eclipse and understand the plugin architecture. But using the agent in a way you described it would of course simplify code complexity.

As for the content assist feature within eclipse (control + space = popup with proposal) - eclipse code completion was a bit of a mystery to me and it was hard to find resources which describe the proper way. but I will have a look if ghost text can be accomplished within this framework.

thank you for your appreciation. one more thing: can you please add the label `hacktoberfest-accepted` to this PR? It would make [hacktoberfest](hacktoberfest.com) awesome ;-) thx.

**Comment by mattifrind** [comment]
Hi, is there any news on this topic? We are using tabby inside our organization and many developers use Eclipse so we are very interested in a plugin for it.

**Comment by icycodes** [comment]
The [Tabby Agent](https://github.com/TabbyML/tabby/tree/main/clients/tabby-agent) has been released on [npm](https://www.npmjs.com/package/tabby-agent), now with [LSP](https://microsoft.github.io/language-server-protocol/) support. There are also configuration samples available to enable the use of Tabby Agent in other text editors. I believe this could be an option for integrating Eclipse with Tabby. 
However, I am not familiar with Eclipse. If anyone wishes to give setting up Eclipse with Tabby Agent a try, I would be glad to provide assistance.

Please feel free to share your thoughts and ask any questions you might have.

**Pull request closed without merging**
