### PR TITLE
feat: Support AMD GPU in docker image

### PR DESCRIPTION
**Pull request by KagurazakaNyaa**
ROCm and CUDA are not suitable for building in the same docker image, so I separated 3 different device types.
Because I don't have a macos device to build and test locally so I didn't add the `metal` type.

### CODE REVIEW

**Comment by wsxiaoys** [comment]
Thanks for the PR. Have you checked our linux binary distribution? It probably an easier way to utilize tabby on linux systems.

**Comment by KagurazakaNyaa** [comment]
> Thanks for the PR. Have you checked our linux binary distribution? It probably an easier way to utilize tabby on linux systems.

Yes, I understand that using the binary distribution directly is an easy way, but then you have to manually manage updates and write systemd units, install rocm or cuda runtimes. Maybe these troubles can be avoided after this project enters the AUR/Debian repository/PPA, but currently the most convenient way is to run the docker container.

**Comment by wsxiaoys** [comment]
Right - I was primarily considering that it could be much easier to create a Docker image for rocm/cpu since we have binary distributions as first-class release artifacts. You could simply download the binary into the Docker container.

I would still maintain the CUDA build as it is for legacy reasons. There are existing systems that rely on the current build behavior for deploying Tabby.

**Comment by KagurazakaNyaa** [comment]
> Right - I was primarily considering that it could be much easier to create a Docker image for rocm/cpu since we have binary distributions as first-class release artifacts. You could simply download the binary into the Docker container.
> 
> I would still maintain the CUDA build as it is for legacy reasons. There are existing systems that rely on the current build behavior for deploying Tabby.

Indeed, maybe I should modify the build method so that the builder step does not build the binary file from the source code but downloads the binary file directly from the GitHub release based on the tag?

**Comment by wsxiaoys** [comment]
One way to do so, is to trigger docker build after https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release event, instead of tag push?

**Comment by KagurazakaNyaa** [comment]
A strange situation occurred. When I used the binary file directly, it seemed that I could not correctly call amdgpu for calculations.
Maybe I should open a new issue to describe this problem.

**Comment by KagurazakaNyaa** [comment]
ref #1404 
I submitted the method of using download instead of building to the download branch, maybe I can test the results on more devices.

**Comment by wsxiaoys** [comment]
close in favor of #1543

**Pull request closed without merging**
