### PR TITLE
Update apple.md

### PR DESCRIPTION
**Pull request by prologic**
Not sure if this is right or not,  but I get an error when following the docs.

```
$ tabby serve --device metal --model TabbyML/CodeLlama-7B
error: invalid value 'metal' for '--device <DEVICE>'
  [possible values: cpu, cuda]
```

### CODE REVIEW

**Comment by wsxiaoys** [comment]
Hi @prologic,

How did you install tabby? Are you installing it from homebrew?

**Comment by prologic** [comment]
Presentingly downloading the latest model 😅
Screenshot 2023-09-14 at 02 53 36

**Comment by prologic** [comment]
Damn it failed :/

```
prologic@JamessMacStudio
Thu Sep 14 02:30:33
~/Projects/selfhosted/tmp/tile38-import
 2
$ tabby serve --device cpu --model TabbyML/CodeLlama-7B
Downloaded /Users/prologic/.tabby/models/TabbyML/CodeLlama-7B/tabby.json
  [00:00:00] [#####################################################################################################################] 143B/143B (83.48 KiB/s, 0s)
Downloaded /Users/prologic/.tabby/models/TabbyML/CodeLlama-7B/tokenizer.json
  [00:00:01] [##############################################################################################################] 1.76 MiB/1.76 MiB (1.59 MiB/s, 0s)
Downloaded /Users/prologic/.tabby/models/TabbyML/CodeLlama-7B/ctranslate2/config.json
  [00:00:00] [#####################################################################################################################] 103B/103B (63.71 KiB/s, 0s)
Downloaded /Users/prologic/.tabby/models/TabbyML/CodeLlama-7B/ctranslate2/model.bin
  [00:25:07] [############################################################################################################] 12.55 GiB/12.55 GiB (8.53 MiB/s, 0s)libc++abi: terminating due to uncaught exception of type std::runtime_error: Unsupported model revision. This executable supports models with revision v6 or below, but the model has revision v7. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
Abort trap: 6
```

**Comment by wsxiaoys** [comment]
Could you share the output of `tabby serve --help`?

**Comment by prologic** [comment]
```console
prologic@JamessMacStudio
Thu Sep 14 02:56:05
~/Projects/selfhosted/tmp/tile38-import
 134
$ tabby serve --help
Starts the api endpoint for IDE / Editor extensions

Usage: tabby serve [OPTIONS] --model <MODEL>

Options:
      --model <MODEL>
          Model id for serving

      --port <PORT>
          [default: 8080]

      --device <DEVICE>
          Device to run model inference

          [default: cpu]
          [possible values: cpu, cuda]

      --device-indices <DEVICE_INDICES>
          GPU indices to run models, only applicable for CUDA

          [default: 0]

      --num-replicas-per-device <NUM_REPLICAS_PER_DEVICE>
          Number of replicas per device, only applicable for CPU

          [default: 1]

      --compute-type <COMPUTE_TYPE>
          Compute type

          [default: auto]

          Possible values:
          - auto:         Set quantization automatically based on device:
          - int8:         Quantize model weights to use int8 for inference
          - float16:      Use float16 for inference, only supported on CUDA devices
          - int8_float16: Use int8 / float16 mixed precision for inference, only supported on CUDA devices

  -h, --help
          Print help (see a summary with '-h')

  -V, --version
          Print version

prologic@JamessMacStudio
Thu Sep 14 03:13:38
~/Projects/selfhosted/tmp/tile38-import
 0
$ command -v tabby
/Users/prologic/bin/tabby
````

Ahh ha! I have an old install of `tabby` 🤦‍♂️

**Comment by prologic** [comment]
This was erroneous 😅 Sorry! `rm ~/bin/tabby` did the trick 👌

**Pull request closed without merging**
