### PR TITLE
fix(intellij): com.intellij.serviceContainer.AlreadyDisposedException

### PR DESCRIPTION
**Pull request by moqimoqidea**
see #1376

### CODE REVIEW

**Comment by icycodes** [comment]
Thank you for the PR!
I will validate it in my environment.

**Comment by moqimoqidea** [comment]
> Thank you for the PR!
> 
> I will validate it in my environment.

Hello, has this pr verification been successful?😄

**Comment by icycodes** [comment]
> > Thank you for the PR!
> > I will validate it in my environment.
> 
> Hello, has this pr verification been successful?😄

After some testing in my environment, I found that the main problem is that the attached `DocumentListener` should not be invoded after the related editor is disposed. I believe we should remove the listener when the editor is released. This way, we will not need to always catch this error.

Additionally, I have found that this problem is related to issue #917. Both issues are caused by a `ContainerDisposedException`. Have you observed any behavior like reverse text typing mentioned in #917, or just a UI freeze?

**Comment by moqimoqidea** [comment]
> > > Thank you for the PR!
> > > I will validate it in my environment.
> > 
> > 
> > Hello, has this pr verification been successful?😄
> 
> After some testing in my environment, I found that the main problem is that the attached `DocumentListener` should not be invoked after the related editor is disposed. I believe we should remove the listener when the editor is released. This way, we will not need to always catch this error.
> 
> Additionally, I have found that this problem is related to issue #917. Both issues are caused by a `ContainerDisposedException`. Have you observed any behavior like reverse text typing mentioned in #917, or just a UI freeze?

Yes, I have encountered the issue of reverse input in my use case, but the frequency is not high compared to freeze.

Thank you very much for your opinion. I just did a bugfix based on the error message from freeze combined with gpt4, and then verified that neither freeze nor reverse input occurred again.

If you have a more reasonable bugfix plan, I think the new plan is better. Haha, because I just solved the problem I encountered without considering a more elegant design at the IDE level.

**Pull request closed without merging**
