### PR TITLE
fix(chat): fix chat stream not closing properly

### PR DESCRIPTION
**Pull request by moqimoqidea**
### Description:

This PR addresses an issue where the chat stream closes prematurely when invoked.

### Affected Versions:

- v14
- v15
- Current v16-dev

### Issue Description:

When using tools like `curl` to invoke the chat stream, it exhibits the following behavior:

```shell
curl -L 'http://localhost:8080/v1/chat/completions' \
-H 'accept: text/event-stream' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer auth_c3b3c321795c41e28e9810eb7115ab9a' \
-d '{
  "messages": [
    {
      "role": "user",
      "content": "hello, there"
    }
  ],
  "model": "local"
}'
data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":"Hello","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":"!","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":" How","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":" can","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":" I","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":" assist","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":" you","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":" today","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":"?","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-c6XNR3r6KNKFqq6m8Rj84lGAM057aUO4","choices":[{"index":0,"delta":{"content":null,"function_call":null,"tool_calls":null,"role":null},"finish_reason":"stop","logprobs":null}],"created":1723616255,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

curl: (18) transfer closed with outstanding read data remaining
```

With this PR applied, the behavior of `curl` is as follows:

```shell
curl -L 'http://localhost:8080/v1/chat/completions' \
-H 'accept: text/event-stream' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer auth_c3b3c321795c41e28e9810eb7115ab9a' \
-d '{
  "messages": [
    {
      "role": "user",
      "content": "hello, there"
    }
  ],
  "model": "local"
}'
data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":"Hello","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":"!","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":" How","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":" can","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":" I","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":" assist","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":" you","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":" today","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":"?","function_call":null,"tool_calls":null,"role":null},"finish_reason":null,"logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}

data: {"id":"chatcmpl-KUaLFe9YcIt06gIcOZX8gGDJstcyAPHL","choices":[{"index":0,"delta":{"content":null,"function_call":null,"tool_calls":null,"role":null},"finish_reason":"stop","logprobs":null}],"created":1723616209,"model":"local","system_fingerprint":null,"object":"chat.completion.chunk"}
```

### CODE REVIEW

**Comment by wsxiaoys** [comment]
It appears that I'm unable to reproduce the error on the current main branch. Could you share your runtime environment details, such as the operating system and curl version, please?

**Comment by moqimoqidea** [comment]
* os: macOS Sonoma Version 14.5
* Chip: Apple M1 Max

curl -V

```shell
curl 8.9.1 (aarch64-apple-darwin23.4.0) libcurl/8.9.1 OpenSSL/3.3.1 (SecureTransport) zlib/1.2.12 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libssh2/1.11.0 nghttp2/1.61.0 librtmp/2.3
Release-Date: 2024-07-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

**Comment by wsxiaoys** [comment]
Thanks for the PR, I proposed another fix https://github.com/TabbyML/tabby/pull/2879 and will merge it soon.

**Comment by wsxiaoys** [comment]
Closing in favor of https://github.com/TabbyML/tabby/pull/2879

**Pull request closed without merging**
