### PR TITLE
feat: separte Dockefile into two

### PR DESCRIPTION
**Pull request by leiwen83**
So that with tabby_base, we could have setup a easy dev environment.

### CODE REVIEW

**Comment by leiwen83** [comment]
@wsxiaoys Could you help review? Now with Dockefile_base, we could have a stable dev docker env.

**Comment by wsxiaoys** [comment]
Hi @leiwen83 

Thank you for the PR. For now, I'd prefer not to recommend a Docker-based development environment for first-time contributors. Setting up a CPU-based environment (without CUDA) is much easier to get started with. I noticed your comments on #409, but it seems you've already resolved the issue (did you need to install `libssl-dev`?).

**Comment by leiwen83** [comment]
> Hi @leiwen83
> 
> Thank you for the PR. For now, I'd prefer not to recommend a Docker-based development environment for first-time contributors. Setting up a CPU-based environment (without CUDA) is much easier to get started with. I noticed your comments on #409, but it seems you've already resolved the issue (after install `libssl-dev`?).

I closed #409 for build from the top is ok and didn't blocking the fastchat integration test, the example still has problem to test with...
I am relative new to rust dev, and notice rust environment is not easy to setup with. So I thought it maybe a good idea to a have dev Dockerfile to put everyone in the same page, even for first-time contributor?

**Comment by wsxiaoys** [comment]
I agree that setting up the Rust environment can be a bit challenging, but I still recommend configuring it in the host environment. This way, the package registry and caching will work seamlessly right from the start.

The [Build](https://github.com/TabbyML/tabby#build) section in the README might be a bit tricky to follow, but instead of adding another layer of complexity, let's work on improving it.

**Comment by leiwen83** [comment]
Got it

**Pull request closed without merging**
